# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 08da98213158f6ade7871a386251f5cf5c532ffdaa808ee611d7e60496d23a9891be9b8f13d8fad991b135fe434f96b052f2e69b062a0054fd5b48d5699cf7d6

test:
  secret_key_base: fb7d52cc8c402538829a07634484dfcd49a12f34b7c521be2bfed1005d05da2febb64f1ca569082077ca60a8fff25de02f0783b1444d850e7ef5e8afc0e7d461

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
